# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]

jobs:
  version-check:
    runs-on: ubuntu-latest
    name: Version Check
    steps:
      - uses: actions/checkout@v2.4.2
      # 检查npm包的版本号和本地packages.json的版本号是否重复
      # https://github.com/marketplace/actions/version-check
      - id: cpv
        uses: PostHog/check-package-version@v2

      - name: cpv false output
        if: steps.cpv.outputs.is-new-version == 'false' || steps.cpv.outputs.committed-version < steps.cpv.outputs.published-version
        run: |
          echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
          echo "Published version: ${{ steps.cpv.outputs.published-version }}"
          echo "Is new version: ${{ steps.cpv.outputs.is-new-version }}"
          exit 1
      - name: cpv output
        if: steps.cpv.outputs.is-new-version == 'true'
        run: |
          echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
          echo "Published version: ${{ steps.cpv.outputs.published-version }}"

  # publish to github package
  publish-gpr:
    needs: version-check
    runs-on: ubuntu-latest
    name: Publish Github Package
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
      - run: npm pkg set publishConfig.registry=https://npm.pkg.github.com
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # publish to npm package
  public-npm:
    needs: version-check
    runs-on: ubuntu-latest
    name: Publish Npm Package
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@example.com"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
